name: Hello World CI

on:
  push:
    branches:
      - main  # Adjust if you use a different branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      - name: Echo Hello World
        run: echo "Hello World"
