name: SSH Test
on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    environment: "Ubuntu in the sky"
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ls -la ~/.ssh/deploy_key  # Debug: check file permissions
          echo "Key file contents (first line only):"
          head -n 1 ~/.ssh/deploy_key  # Debug: verify key starts correctly
          ssh-keygen -l -f ~/.ssh/deploy_key || echo "Invalid key format"  # Debug: validate key
      - name: Add host key
        run: ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Test Connection
        run: |
          ssh -v -i ~/.ssh/deploy_key -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} whoami
          cd /var/www/portfolio
          git pull